{
  "formatVersion": "1.1",
  "component": {
    "group": "org.example",
    "module": "utils",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-1.3.5.jar",
          "url": "utils-1.3.5.jar",
          "size": 969,
          "sha512": "d52c907fa205524a2eda75233b7582059b14a2b3b3322c944c108d7774ba1e51b23f14b1afd7c1be2241a0b8f812591e9edc5ec80310a4000659308cf86024b5",
          "sha256": "8bba99b0dd37e0c45fd9b8df1bea25710fd6701ea2b51cde0644b1772a5f88ea",
          "sha1": "0eb86495bddf086ddce888ea0bb55beb9c1a01d4",
          "md5": "404a109265374a7eacc6d88993a58157"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-1.3.5.jar",
          "url": "utils-1.3.5.jar",
          "size": 969,
          "sha512": "d52c907fa205524a2eda75233b7582059b14a2b3b3322c944c108d7774ba1e51b23f14b1afd7c1be2241a0b8f812591e9edc5ec80310a4000659308cf86024b5",
          "sha256": "8bba99b0dd37e0c45fd9b8df1bea25710fd6701ea2b51cde0644b1772a5f88ea",
          "sha1": "0eb86495bddf086ddce888ea0bb55beb9c1a01d4",
          "md5": "404a109265374a7eacc6d88993a58157"
        }
      ]
    }
  ]
}
