{
  "formatVersion": "1.1",
  "component": {
    "group": "org.example",
    "module": "utils",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-1.3.5.jar",
          "url": "utils-1.3.5.jar",
          "size": 972,
          "sha512": "ce823699d85c7bb993b110091a8533f9c97efc9e4c0a9e187b342c45601cf8aef1cce777a14ff4f394206c435eb963ef3c71fc3dac00fa19858bfabbd28f643b",
          "sha256": "f8c6246e818e34a9b1809461562e68c78781cd6bf9439bc2e0b8840a3a086abf",
          "sha1": "f669c6d08bf982215fb9811e11692fef2945fc46",
          "md5": "c046e42d0e445d2a5389e96190f60b99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-1.3.5.jar",
          "url": "utils-1.3.5.jar",
          "size": 972,
          "sha512": "ce823699d85c7bb993b110091a8533f9c97efc9e4c0a9e187b342c45601cf8aef1cce777a14ff4f394206c435eb963ef3c71fc3dac00fa19858bfabbd28f643b",
          "sha256": "f8c6246e818e34a9b1809461562e68c78781cd6bf9439bc2e0b8840a3a086abf",
          "sha1": "f669c6d08bf982215fb9811e11692fef2945fc46",
          "md5": "c046e42d0e445d2a5389e96190f60b99"
        }
      ]
    }
  ]
}
