{
  "formatVersion": "1.1",
  "component": {
    "group": "org.example",
    "module": "utils",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-1.3.5.jar",
          "url": "utils-1.3.5.jar",
          "size": 969,
          "sha512": "5be0b5c215bbf0d40f27653a5425db8039c871c57ba8acdc5dc335fbb0674a383fc01cbb80c73b97b5cf5c9406839e1f11369156084778c1cab772916c7555b3",
          "sha256": "b162c1be724caf85dcefca15a896b9d8c900ad5e4ff3884621c8b44c9edc3c07",
          "sha1": "f8eeb4ce65acf5b4e42268456eb3aa46cc016975",
          "md5": "0ace5b440da509e7f0e4e947a7ae5d66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-1.3.5.jar",
          "url": "utils-1.3.5.jar",
          "size": 969,
          "sha512": "5be0b5c215bbf0d40f27653a5425db8039c871c57ba8acdc5dc335fbb0674a383fc01cbb80c73b97b5cf5c9406839e1f11369156084778c1cab772916c7555b3",
          "sha256": "b162c1be724caf85dcefca15a896b9d8c900ad5e4ff3884621c8b44c9edc3c07",
          "sha1": "f8eeb4ce65acf5b4e42268456eb3aa46cc016975",
          "md5": "0ace5b440da509e7f0e4e947a7ae5d66"
        }
      ]
    }
  ]
}
