{
  "formatVersion": "1.1",
  "component": {
    "group": "org.example",
    "module": "CustomPlugin",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CustomPlugin-3.0.jar",
          "url": "CustomPlugin-3.0.jar",
          "size": 1852,
          "sha512": "75460ca7ae84c227bac8e6c1ec2a89767e7705380fa9905e7406107a21ea25a8d92d73ab7fee30b72b5fb2106c01f8a055fdbcba068a423f656d82c2523f0ad2",
          "sha256": "694e043ed1b469ddd6f30164f9d125703f21e3df681e578e79af7533232c8ece",
          "sha1": "252abd29599c8a8443b9da1eee53e6fa9ce3cde9",
          "md5": "767d070dd81d05e78f9bc2ba23ec7a01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CustomPlugin-3.0.jar",
          "url": "CustomPlugin-3.0.jar",
          "size": 1852,
          "sha512": "75460ca7ae84c227bac8e6c1ec2a89767e7705380fa9905e7406107a21ea25a8d92d73ab7fee30b72b5fb2106c01f8a055fdbcba068a423f656d82c2523f0ad2",
          "sha256": "694e043ed1b469ddd6f30164f9d125703f21e3df681e578e79af7533232c8ece",
          "sha1": "252abd29599c8a8443b9da1eee53e6fa9ce3cde9",
          "md5": "767d070dd81d05e78f9bc2ba23ec7a01"
        }
      ]
    }
  ]
}
