{
  "formatVersion": "1.1",
  "component": {
    "group": "org.example",
    "module": "utils",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-1.1.5.jar",
          "url": "utils-1.1.5.jar",
          "size": 1036,
          "sha512": "d797aebb93dff9390b0035089b96a4c089c933896cedc9ffe940fb5a99753697db0bc1ded132577a9f4ea9c4107a37f0fad5416b6e1dbf26b62f3fc223d9eb09",
          "sha256": "13ee7a2bc0dcce51ab727602fe1abc79a18f31889c8aeb5982303ed93037a2c4",
          "sha1": "d3fd194fd82c3429929f49529d322bde8b840f20",
          "md5": "0bb7999416eb6825512de0905959a560"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-1.1.5.jar",
          "url": "utils-1.1.5.jar",
          "size": 1036,
          "sha512": "d797aebb93dff9390b0035089b96a4c089c933896cedc9ffe940fb5a99753697db0bc1ded132577a9f4ea9c4107a37f0fad5416b6e1dbf26b62f3fc223d9eb09",
          "sha256": "13ee7a2bc0dcce51ab727602fe1abc79a18f31889c8aeb5982303ed93037a2c4",
          "sha1": "d3fd194fd82c3429929f49529d322bde8b840f20",
          "md5": "0bb7999416eb6825512de0905959a560"
        }
      ]
    }
  ]
}
